const mongoose=require('mongoose')
const {Schema}=mongoose

const Student=new Schema({
    division_id:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'divisions',
        required:true
    },
    our_reg_no:{
        type:String,
        required:true
    },
    date_of_admission:{
        type:Date,
        default:Date.now
    },
    student_name:{
        type:String,
        required:true
    },
    address:{
        type:String,
        required:true

    },
    image:{
        type:String,
        required:false
    },
    whatsup:{
        type:Number,
        required:true
    },
    contact_no1:{
        type:Number,
        required:true
    }
    ,
    contact_no2:{
        type:Number,
        required:false
    },
    email_id:{
        type:String,
        required:true
    },
    parent_or_guardian_name:{
        type:String,
        required:true
    },
    parent_contact:{
        type:Number,
        required:true
    },
    
    course_id:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'courses'
    },
    university_reg_no:{
        type:Number,
        required:true
    },
    college_id:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'colleges'
    },
    fees:{
        type:Number,
        required:true
    },
    paystatus:{
        type:String,
        required:false
    },
    reg_fees:{
        type:Number,
        required:true
    },
    status:{
        type:String,
        required:true
    },
    created_at:{
        type:Date,
        default:Date.now
    },
    updated_at:{
        type:Date,
        required:false
    },
    place:{
        type:String,
        required:true
    },
    p_address:{
        type:String,
        required:true
    },
    t_pincode:{
        type:Number,
        required:true
    },
    t_district:{
        type:String,
        required:true
    },
    t_state:{
        type:String,
        required:true
    },p_pincode:{
        type:Number,
        required:true
    },
    p_district:{
        type:String,
        required:true
    },
    p_state:{
        type:String,
        required:true
    },
    relationship :{
        type:String,
        required:true

    },
    stream:{
        type:String,
        required:true
    },
    sem:{
        type:String,
        required:true
    },
    status_student:{
        type:String,
        required:false
    },
    all_status:{
        type:String,
        required:false
    }
})

module.exports=mongoose.model("students",Student)