const mongoose=require('mongoose')
const {Schema}=mongoose

const Student=new Schema({
    division_id:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'division',
        required:false
    },
    batch_id:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'batch',
        required:false
    },
    our_reg_no:{
        type:String,
        required:false
    },
    date_of_admission:{
        type:Date,
 
        required:false
    },
    student_name:{
        type:String,
        required:false
    },
    address:{
        type:String,
        required:false

    },
    image:{
        type:String,
        required:false
    },
    whatsup:{
        type:Number,
        required:false
    },
    contact_no1:{
        type:Number,
        required:false
    }
    ,
    contact_no2:{
        type:Number,
        required:false
    },
    email_id:{
        type:String,
        required:false
    },
    parent_or_guardian_name:{
        type:String,
        required:false
    },
    parent_contact:{
        type:Number,
        required:false
    },
    
    course_id:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'courses'
    },
    project_id:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'project_details'

    },
    university_reg_no:{
        type:String,
        required:false
    },
        college_id:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'colleges'
        },
    fees:{
        type:Number,
        required:false
    },
    pending_fees:{
        type:Number,
        required:false

    },
    paystatus:{
        type:String,
        required:false
    },
    reg_fees:{
        type:Number,
        required:false
    },
    status:{
        type:String,
        required:false
    },
    created_at:{
        type:Date,
        default:Date.now,
        required:false
    },
    updated_at:{
        type:Date,
        required:false
    },
    t_address:{
        type:String,
        required:false
    },
    p_address:{
        type:String,
        required:false
    },
    t_pincode:{
        type:Number,
        required:false
    },
    t_district:{
        type:String,
        required:false
    },
    t_state:{
        type:String,
        required:false
    },p_pincode:{
        type:Number,
        required:false
    },
    p_district:{
        type:String,
        required:false
    },
    p_state:{
        type:String,
        required:false
    },
    relationship :{
        type:String,
        required:false

    },
    stream:{
        type:String,
        required:false
    },
    sem:{
        type:String,
        required:false
    },
    status_student:{
        type:String,
        required:false
    },
    all_status:{
        type:String,
        required:false
    }
})

module.exports=mongoose.model("students",Student)